# Generated by Django 4.0.3 on 2022-04-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blogsite with Django', max_length=255),
        ),
    ]
